-- Modules/DadJokes.lua - Dad Jokes Module

Dadabase = Dadabase or {}

local defaultJokes = {
    "What do ducks like on their tacos? Quackamole and Beako de Gallo",
    "Did you know Vin Diesel only eats 2 meals a day? BreakFAST and BreakFURIOUS!",
    "I don't like German sausages. They are the wurst",
    "Which vegetable do you stand in line for? A queue cumber.",
    "Everyone knows Albert Einstein was brilliant. His brother Frank, though, was a real monster.",
    "My wife says I'm the cheapest man in the world. Well, I'm not buying it.",
    "The Flat Earth Society just announced they now have one million members...around the globe.",
    "What do you call a funny drawing? A Snickerdoodle",
    "A friend asked me to play the part of Brutus in an upcoming play about Julius Caesar.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What do you call a sad strawberry? A blueberry.",
    "My physical therapist said I should do lunges to stay in shape. That would be a big step forward.",
    "I asked my dog what's two minus two. He said nothing.",
    "Did you know the first French fries weren't cooked in France? They were cooked in Greece.",
    "Where do you learn to make a banana split? Sundae school.",
    "Do you know why koala bears aren't really bears? They don't meet the koalafications.",
    "I used to be addicted to soap, but I'm clean now.",
    "What do you call it when a snowman throws a tantrum? A meltdown.",
    "Bought a new shrub trimmer today... It's cutting hedge technology.",
    "Did you hear about the circus fire? It was in tents.",
    "How can you tell it's a dogwood tree? By the bark.",
    "Don't trust atoms. They make up everything!",
    "What kind of car does a sheep like to drive? A lamborghini.",
    "If the early bird gets the worm, I'll sleep in until there's pancakes.",
    "I don't trust stairs. They're always up to something.",
    "Every time I take my dog to the park, the ducks try to bite him. That's what I get for buying a pure bread dog.",
    "Time flies like an arrow. Fruit flies like a banana.",
    "I used to hate facial hair, but then it grew on me.",
    "Most people can't tell the difference between entomology and etymology. I can't find the words for how much this bugs me.",
    "We're renovating the house, and the first floor is going great, but the second floor is another story.",
    "At first, I thought my chiropractor wasn't any good, but now I stand corrected.",
    "What breed of dog can jump higher than a skyscraper? Any breed of dog. Skyscrapers can't jump.",
    "What's the best way to watch a fly-fishing tournament? Live Stream",
    "I have a joke about chemistry, but I don't think it'll get a reaction.",
    "I have a joke about a broken pencil, but it's pointless.",
    "My cousin just quit his job as a lawyer to become a dog breeder. It turns out... He prefers Boxers over Briefs.",
    "I have a joke about the flu, but I hope you don't get it.",
    "I have a joke about drilling, but it's boring.",
    "I have a joke about procrastination, but I'll tell it to you later.",
    "I went to my boss's funeral... I kneeled down next to the coffin and whispered, 'Now who's thinking outside the box?'",
    "I have a joke about butter, but I'm not going to spread it.",
    "I could tell a joke about pizza, but it's a little cheesy.",
    "Don't buy anything made with Velcro. It's a total rip-off.",
    "I used to be addicted to the hokey pokey, but then I turned myself around.",
    "What do you call a donkey with only three legs? A wonkey.",
    "To whoever stole my copy of Microsoft Office, I will find you. You have my Word.",
    "What are the strongest days of the week? Saturday and Sunday. The rest are weak-days.",
    "Why do ducks have tail feathers? To cover their buttquacks.",
    "Why did the sailors have to stop playing cards? The Captain was standing on the deck",
    "This graveyard looks overcrowded. People must be dying to get in there.",
    "What's brown and sticky? A stick.",
    "I just found out that Albert Einstein was a real person! I thought he was a theoretical physicist.",
    "Took my kids to the zoo and my son saw a tiger sleeping. I told him it's a Himalayan Tiger. My son asks me how do I know? Because him-a-layin right there.",
    "Why was the math textbook so sad? It had so many problems!",
    "Scientists recently combined DNA of a cheetah with the DNA of a crab. Things went sideways real fast.",
    "I just moved twenty cents from my left pocket to my right. It was a pair o'dime shift.",
    "I decided to sell my vacuum cleaner. It was just gathering dust.",
    "Why is a doctor always calm? Because they have a lot of patients.",
    "Five out of four people admit they're bad with fractions.",
    "Why did the employee get fired from the keyboard factory? He wasn't putting in enough Shifts.",
    "My uncle had a tragic accident at work, he fell into the upholstery machine. Did he die? No, he's fully recovered.",
    "I told my friend she drew her eyebrows too high. She seemed surprised!",
    "Don't sing in the shower!  If you get soap in your mouth, it will turn into a soap opera.",
    "Did you ever notice ants don't get sick? They're full of anty-bodies.",
    "A man fell into a meat grinder, becoming a sausage. That's quite a dumb way to die, to be frank.",
    "What did the mommy buffalo say to her son when he left for work? Bison.",
    "It really takes guts to be an organ donor.",
    "I got fired from my job as a masseur. Apparently I rub people up the wrong way.",
    "How do you deal with a fear of speed bumps? You slowly get over it.",
    "What happens when a snowman throws a tantrum? He has a meltdown.",
    "You can't trust atoms. They make up everything!",
    "How do astronomers organize a party? They planet.",
    "Spouse asked me how I would like my eggs, scrambled or fried. I said I didn't care. I said I'm eggnostic.",
    "You know what? Cottage cheese isn't really a cheese. It's just a curd to me.",
    "What do you call a dog that digs up really old bones? A barkaeologist",
    "You can tell it is a dogwood tree from its bark.",
    "I just don't trust stairs, they're always up to something.",
    "My daughter screeched, 'Daaaaaad, you haven't listened to one word I've said, have you!?' What a strange way to start a conversation with me...",
    "A slice of apple pie is $2.50 in Jamaica and $3.00 in the Bahamas. These are the pie rates of the Caribbean.",
    "My friend keeps saying 'cheer up druid it could be worse, you could be stuck underground in a hole full of water.' I know he means well.",
    "What does a zombie vegetarian eat? 'GRRRAAAAAIIIINNNNS!'",
    "I've lost control… I don't see an end… There's no escape… I don't even have a home anymore. Sigh... Guess it's time to buy a new keyboard.",
    "What did the pirate say on his 80th birthday? AYE MATEY",
    "How many tickles does it take to make an Octopus laugh? Tenticles",
    "Wondering if they're ticklish? Test-tickles are a great place to start.",
    "I've just written a book called 'Fifty Shades of Gravy' It's very saucy.",
    "The adjective for metal is metallic. But not so for iron... which is ironic.",
    "Welcome to the Sexual Innuendo Club. Thank you all for coming.",
    "My house got robbed and one of the items missing was my limbo set. I thought to myself... how low can these guys go?",
    "I called the paranoia hotline and they answered, 'How did you get this number?'",
    "What's a plumber's least favourite vegetable? Leeks.",
    "I had a fun childhood. My friends used to push me down the hill in old tires. They were Goodyears.",
    "Dentists always ask dumb questions like 'When's the last time you flossed?' Like dude, you were there!",
    "I got tired of being judged for going bald so I went out and bought a cheap wig... It was a small price toupée",
    "I once entered the world kleptomaniac championships. I took gold, silver, and bronze.",
    "I'm french and just moved abroad, people are pretty insensitive here and always joke about baguettes. They don't care that they're laughing at my pain.",
    "Does anybody know where a guy can find a person to hang out with, talk to, and enjoy spending time with? Asking for a friend.",
    "I've got a German friend who's a sound technician. I've got a Czech one too. Czech one too.",
    "I asked my wife if I was the only one she had ever been with. She said yes, all the others were nines and tens.",
    "I returned my lizard to the pet store as he wouldn't stop telling dad jokes. That's not a lizard, the store clerk told me. That's a stand-up chameleon.",
    "It's a five minute walk from my house to the pub, and it's a 35 minute walk from the pub to my house. The difference is staggering.",
    "Did you know that your pupils are the last parts to stop working after you die? They dilate.",
    "Interviewer: why should we hire you as a waiter? Me: For starters, I bring a lot to the table.",
    "I've just discovered that Bruce Lee had a vegetarian brother... Broco Lee.",
    "I started reading a horror story in braille. Something bad is about to happen, I can feel it.",
    "Why is the divorce rate so high with tennis players? To them, Love means nothing.",
    "'Trojan' isn't a good name for a condom. Didn't the real Trojan horse burst and loads of little guys came pouring out of it?",
    "What do you call a line of men waiting to get haircuts? A barberqueue.",
    "What do you call sweaty boobs? Humidititties.",
    "How much does a rainbow weigh? Not much, they're actually pretty light!",
    "My friend blocked me on Facebook because I post too many bird puns. Well, toucan play at that game.",
    "I hate when my friends gets mad at me for being lazy. It's not like I did anything.",
    "Many people are too judgemental... I can tell just by looking at them.",
    "I accidentally drank a bottle of invisible ink last night. I'm in the hospital now, waiting to be seen.",
    "Who hides in the bathroom at parties? The party-pooper.",
    "Someone has glued my pack of cards together... I don't know how to deal with it.",
    "I hate my job. All I do is crush cans all day. It's soda pressing.",
    "Went for a job interview today, at IKEA.  The manager said: 'Come in, make a seat.'",
    "My friend went bald years ago, but still carries his old comb with him. He just can't part with it.",
    "My wife is thinking of leaving me because of my obsession with poker but I think she's bluffing.",
    "What do you call two monkeys who share an Amazon account? Prime mates.",
    "What do you call a short mother? A minimum.",
    "I don't mean to brag, but... cashiers are always checking me out.",
    "I was just looking at my ceiling. Not sure if it's the best ceiling in the world, but it's definitely up there.",
    "I've started telling everyone about the health benefits of eating dried grapes. It's all about raisin awareness.",
    "I was going to propose to my girlfriend, but my dog ate the ring. Now it's a diamond in the ruff.",
    "I had to fire the guy I hired to mow my lawn. He just didn't cut it.",
    "I made a graph showing all my past relationships. It has an ex-axis and a why-axis.",
    "My friend has accused me of stealing her Thesaurus. Not only was I shocked, I was also aghast, appalled and dismayed.",
    "People call me self centred. But that's enough about them.",
    "My girlfriend complains a lot that I don't smile anymore. Well she's the one who wanted a serious relationship.",
    "It hurts me to say this, but... I have a sore throat.",
    "Tequila might not be the answer but it's worth a shot.",
    "What kind of doctor is Dr. Pepper? A fizzician.",
    "People say being a waiter is a bad job... but, hey, it puts food on the table.",
    "Atheism is a non-prophet organization.",
    "What's more amazing than a talking dog? A spelling bee.",
    "A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.",
    "Once you've seen one shopping center, you've seen the mall.",
    "A plateau is the highest form of flattery.",
    "I didn't like my beard at first. Then it grew on me.",
    "My dolphin puns are terrible on porpoise.",
    "Why can't you play poker on the African Savanna? There's too many cheetahs.",
    "I've deleted the phone numbers of all the Germans I know from my mobile phone. Now it's Hans free.",
    "Breaking news! Energizer Bunny arrested - charged with battery",
    "Have you ever heard of a music group called Cellophane? They mostly wrap.",
    "I went to the zoo the other day, there was only one dog in it. It was a shitzu.",
    "I like looking in the mirror... it's good to reflect sometimes.",
    "Is it strange how saying sentences backwards creates backward sentences saying how strange it is?",
    "What's the sleepiest paper? A napkin",
    "What type of bees produce milk?  Boobies",
    "A lady just dropped a steak while I was at the store. I said, 'whoops, that must be ground beef!'",
    "Two moles are crawling down a mole hole. The second mole tells the first mole, 'It smells like molasses down here!'",
    "I'm afraid for the calendar. Its days are numbered.",
    "Dear Math, grow up and solve your own problems.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
    "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
    "I ordered a chicken and an egg from Amazon. I'll let you know...",
    "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
    "The other day a clown held the door open for me. It was a nice jester.",
    "How does a programmer lose his mind? Bit by bit.",
    "Why do treehouses make good businesses? They typically have good branch managers.",
    "Why did the non-binary prospector head west? There was gold in them/their hills!",
    "My kids asked me what 'opaque' means. I said that according to the dictionary, it's still unclear.",
    "My spouse asked me why our fridge was full of stir fry this morning. Turns out I was sleep wokking again.",
    "I'm desperately trying to find out who's been pooping on my lawn. It's a real who dung it.",
    "I got home after programming all day and my spouse asked me to buy somethings in the grocery store. He said 'Buy a gallon of milk, if there are apples, buy 12'. Then he got mad at me when I show up at home with 12 gallons of milk.",
    "My pet-collecting friend went missing in a horse barn. We suspect foal play.",
    "I signed up for this new subscription service where I receive new tires on a regular basis. It's my retirement plan.",
    "I want to tell you a salty joke. On second thought, Na.",
    "Every morning at the breakfast table, I tell my kids I'm going for a jog, but then I don't. It's a running joke.",
    "Someone made the mistake of bringing his attack dog to the circus. As might have been expected, it went straight for the juggler.",
    "My daughter asked for me to hand her her lipstick but I accidentally passed her a glue stick. She's still not talking to me.",
    "What has more letters than the alphabet? The Dalaran mail room.",
    "Where do shamans go to get an education? Elementary school",
    "Worrying about my insomnia is keeping me up all night.",
    "I'm not bragging or anything, but I made six figures this year. So they named me the year's worst employee at the toy factory.",
    "I somehow managed to make it through high school math while only being able to remember even numbers! What are the odds?!",
    "What do you call an unimpressed robot? Sighborg",
    "I used to be addicted to elevators. Now Im taking steps to avoid them.",
    "If towels could tell jokes... They'd have the driest sense of humor.",
    "There are 10 types of people in this world: those who understand binary, and those who don't",
    "The programmer got stuck in the shower because the instructions on the shampoo bottle said: Lather, rinse, repeat",
    "What happens when you read a book about anti-gravity? You cannot put it down",
    "Someone keeps sending me flowers with the heads cut off... I think a druid is stalking me",
    "Did you know that rocky mountain oysters are the original sack lunch?",
    "I'm really excited for the amateur autopsy club I just joined. Tuesday is open Mike night",
    "My roommate says I have schizophrenia. Jokes on him, I don't have a roommate.",
    "It was just confirmed that the man who fell off the 30th floor roof of a night club... was not a bouncer",
    "I used to hate long hair, but then it grew on me.",
    "Breaking news! Energizer Bunny arrested! Charged with battery",
    "If a child refuses to nap, are they guilty of resisting a rest?",
    "Do you think there will ever be a time when people stop mistaking Zelda for Link? Personally, I think it's Hylian likely.",
    "To the person who stole my place in the queue. I'm after you now.",
    "Did you hear about the lion who ate his family? He swallowed his pride",
    "What do you call a forsaken without a body and a nose? Nobody nose",
    "I hear they've made a new artificially intelligent Oreo. It's one smart cookie.",
    "What do you get when you cross a wall unit with artificial intelligence? Shelf-awareness.",
    "I built my own glasses. But I don't want to make a spectacle of it.",
    "How do you know someone's been playing since Vanilla? Don't worry, they'll tell you.",
    "You might be an engineer if... If you've used coat hangers and duct tape for something other than hanging coats and taping ducts",
    "How do snails fight? They slug it out",
    "Do you understand how crypto currency works? I'm a bitcoinfused",
    "I can always tell when someone is lying just by looking at them. I can tell when they're standing too",
    "An astronaut walks into a space bar and sees everyone on the floor. It was then where he realized the gravity of the situation",
    "I think I am too emotionally attached to onions. I cry every time I cut them",
    "Dogs can't read MRIs But catscan",
    "I've started telling people about the benefit of dried grapes. It's all about raisin awareness",
    "Where do rainbows go when they're bad? Prism. It's a light sentence.",
    "Why is it called getting your dog fixed when it doesn't work no more afterward?",
    "What starts with E and ends with E, but only has one letter in it? Envelope",
    "RIP boiling water: You will be mist",
    "I got fired on my first day at the bank. A customer asked me to check her balance, so I pushed her over",
    "How many ears does captain Kirk have? Three: His left ear, his right ear and his final frontier",
    "I had a fun childhood. My siblings used to push me down the ski slope in old tires. They were Goodyears.",
    "What did the janitor say when he jumped out of the closet? 'Supplies!'",
    "Have you heard about the chocolate record player? It sounds pretty sweet.",
    "I'm not always what I eat, but sometimes... I yam.",
    "The shadowlands get their own cookies! They're called Oreobos",
    "I've been pressing tomatoes on my stuff for three days now... But I still can't find any of this ketchup gear everyone's been talking about!",
    "I tried calling the tinnitus helpline: I got no answer, just heard ringing.",
    "Why do programmers prefer dark theme? Because light attracts bugs",
    "I told my spouse to embrace their mistakes so they hugged me.",
    "If you think your microwave and your TV spying on you is bad... Your vacuum cleaner has been gathering dirt on you for years",
    "I bought a universal remote today. I was disappointed to find out that it does not, in fact, control the universe. Not even remotely.",
    "The Fibonacci convention is supposed to be pretty special this year. They say it's going to be as big as the last 2 put together.",
    "You would think that a snail mount without a shell would move that bit faster? But it's actually more sluggish.",
    "People always ask rouges how they can sneak chocolate into movie theatres. Well lets just say, they have a few Twix up their sleeves.",
    "A bad workman always blames his fools... *Tools!! *I meant tools!! Stupid keyboard...",
    "For the last eight years I've been voted the most secretive employee in the office by my coworkers. Can't tell you how much this award means to me.",
    "What emotion does a depressed cantaloupe feel? Meloncholy",
    "Why do chicken coops have two doors? Because if they had four they would be chicken sedans.",
    "The inventor of the USB stick has died. Thanks for the memory",
    "How many software engineers does it take to change a light bulb? None. That's a hardware issue",
    "When I wrote this code, only me and God knew how it works. Now only God knows",
    "Conventional wisdom: If it ain't broke, don't fix it. Developer: If it ain't broke, consider adding more features",
    "What's a hydraulic ram used for? It's where you get steel wool!",
    "Never argue with Pi, it's irrational",
    "What do you call a mechanical shovel? Ground-breaking technology!",
    "Old software engineers never die... They just reboot",
    "What did the mechanical frog battle pet say? Rivet Rivet",
    "I have some crockery that has photos of developers drinking gin. They're tech-tonic plates",
    "What do you calla psychic gome who excapes from jail? A small medium at large",
    "What do you NEVER buy at a yard sale? Meters",
    "Dark humor is like clean water. Not everyone gets it",
    "I had a debate with a flat earther. He said he'll walk to the edge of the earth to prove me wrong. Im sure he'll come around",
    "The Beastie Boys are releasing a 5 part anthology. Parts A-D are free, but you have to fight for your right to Part E",
    "My neighbor's house got broken into last night but they only stole their fruit bowl. They're absolutely peachless",
    "I saw someone stealing from an Apple store. I guess that makes me an iWitness",
    "How do programmers decide what to wear to work? They have a dress code",
    "What's the smallest kind of bear? The bear minimum.",
    "My spouse has stood beside me for 20 years.. We only have one chair in the house",
    "When I raid I never worried about my fingers. I can always count on them",
    "I bought some chicken drumsticks. Now I just need to find a chicken that plays the drums",
    "What do you call a death knight who shows up out of nowhere? Sir-prise",
    "I recently had a toe amputated and replaced with a prosthetic made out of a breath mint. Now I have a Tic Tac toe",
    "The past, the present and the future walked into a bar. It was very tense.",
    "My grandma replaced her chair with a bean bag. I think she is off her rocker",
    "Someone broke into the police station and stole all the toilets. Police say they have nothing to go on.",
    "Windows make terrible liars.... You can see right through them",
    "I was going to make a joke about bland food but then I realized it was just tasteless",
    "A hunter killed 11 rabbits. They were very odd, but they were prime",
    "The doctor said I got the peek-a-boo virus. They sent me straight to ICU",
    "At my son's fourth birthday party I didn't recognize him. I'd never seen him be four.",
    "Never yell into a colander. You'll strain your voice.",
    "I was napping under a citrus tree. It was sublime.",
    "What do you call an illegally parked frog? Toad",
    "I hate how funerals are always at 9 a.m. I'm not really a mourning person.",
    "Vegetable oil is made from vegetables. olive oil is made from olives. Baby oil is cruel.",
    "My grandpa died in an Italian restaurant. I guess he pasta way",
    "A wise man once told me you should give 100 percent at everything you do unless you're donating blood",
    "I hate peer pressure and you should too",
    "They say one person in each group of friends had the potential to be a serial killer... So I pushed Dave off a cliff, just in case it was him.",
    "What do you call a comedian who never comes out of the house? An inside joke",
    "Tequila is not the answer... But it's worth a shot.",
    "Some bananas are difficult to open. I find this unappealing",
    "I'd moustache you a question but I'm shaving it for later",
    "I fired the janitor for smoking pot because I can't stand high maintenance people.",
    "What do you call boots made out of bananas? Slippers",
    "The salesman at the furniture store told me, 'This sofa will fit 5 people without any problem.'I said, 'Where the hell am I going to find 5 people without any problems from?'",
    "Why does piglet smell? Because he plays with Pooh!",
    "Did you know that artificial orange juice was first invented in Ancient China... during the Tang Dynasty",
    "I'm addicted to brake fluid but it's okay, I can stop at any time.",
    "I asked my friend if he was gay. He didn't give me a straight answer",
    "I was about to post a joke about Sodium, but I was like Na, people wouldn't get it.",
    "What is Bigfoot's favorite exercise? Sasquats",
    "A weasel walks in to a bar. Bartender is in shock 'Wow, I've never served a weasel before! What'll it be?' The weasel looks the bartender straight in the eye. 'Pop', goes the weasel.",
    "What do you call a red-head ninja? A ginja!",
    "What do you call an Irishman who is bouncing off the walls? Rick O'Shea.",
    "Ban pre-shredded cheese.  Make america grate again!",
    "I sued an airline when my luggage went missing. I lost my case.",
    "Two guys got arrested for stealing a calendar. They both got six months",
    "What is the difference between an alligator and a crocodile? You'll see one in a while, and the other a bit later.",
    "My friend, Jim, drowned last week. We placed a life jacket on his coffin... It's what he would have wanted.",
    "I lost my pickle! Whatever, It's not a big dill.",
    "I lost my wife's audiobook last night... now I'm never going to hear the end of it",
    "What is a duck's favorite snack? Quackers",
    "A guy tried selling me a coffin. That's the last thing I need.",
    "My cows stopped making milk last week! It's an udder disaster!",
    "How do you spot a blind man on a nude beach? It's not hard.",
    "Why did Mr Ohm marry Mrs Ohm? Because he couldn't resistor.",
    "I'm suing Starbucks for bad coffee. Their lawyer wants to know on what grounds.",
    "I brought mushrooms to a party yesterday. They can really make you a fungi.",
    "What's the difference between ignorance and apathy? I don't know and I don't care",
    "I saw a poor old woman trip and fall today. At least I assume she was poor. She only had five dollars in her wallet.",
    "What happens if the school bully walks into a statistics class? The mean increases.",
    "My girlfriend has left me because she thinks I have an obsession with gambling... I bet you she'll be back.",
    "I'll never forget what my grandad said just before he kicked the bucket. 'Watch how far I can kick this bucket!'",
    "If you fall in love with someone from South Korea are they your Seoul mate?",
    "My wife kicked me out because of my terrible Arnold Schwarzenegger impressions, but don't worry. I'll return.",
    "When my wife caught me standing on the bathroom scales, sucking in my stomach, she laughed, 'That's not going to help!' I replied, 'Sure, it does, it's the only way I can see the numbers.'",
    "A Mexican magician says he will disappear on the count of 3. He says 'uno, dos...' *poof*. He disappeared without a tres.",
    "The worst part about kissing a perfect 10 is how cold the mirror feels on my lips.",
    "I got hit with a pickaxe. It's just a miner injury.",
    "Why don't Mummies take vacations? They can't unwind.",
    "I hate it when my friend suddenly says 'Are you even listening to me?' I mean, who the hell starts a conversation like that?",
    "I bought my wife a fridge as an anniversary present. I can't wait to see her face light up when she opens it.",
    "I'm using only fans right now and it's hot. I'm waiting for a technician to get my air conditioner fixed.",
    "Bruce Lee was fast, but he had three even faster brothers. Quik Lee, Sudden Lee and Instant Lee",
    "SpongeBob may be the main character of the show. But Patrick is the star.",
    "My wife left me because I'm too insecure. No wait, she's back. She just went out to bring me a cake.",
    "To whoever stole my depression medication: I hope you're happy.",
    "My spouse had a vasectomy because I didn't want any kids. When I got home, they were still there.",
    "My boss asked me why I only get sick on work days. I said it must be my weekend immune system.",
    "I've just invented the first thought controlled air freshner. It makes scents, when you think about it.",
    "My friend got me a jar of dirt for my birthday. I told them I appreciate the sediment.",
    "My dog swallowed a whole bag of Scrabble tiles. We took him to the vet to get him checked out. No word yet.",
    "I knew a tattoo artist that would give free tattoos to women that flashed him their boobs. It was a real tit for tat situation.",
    "Told my boss 3 companies are after me so I need a pay rise. He asked me which 3 companies they were. I told him, 'Gas, electric & water'",
    "I can always tell when someone is lying just by looking at them. I can tell when they're standing too.",
    "What do you call a man that has been married and divorced multiple times? Lord of the Rings.",
    "Super Mario is Japanese, so technically his last name is Mario. His first name is Itsumi, making him Itsumi Mario.",
    "What do you use to clean a pig? Ham sanitizer",
    "Our local priest charges 10 dollars for every sin he correctly guesses you'll confess to. It's the price of admission",
    "I paid $300 to rent a limo, but that didn't include the driver. All that money and nothing to chauffeur it.",
    "How do you make your water bed bouncier? You add spring water!",
    "Did you hear about the origami teacher who quit? Too much paperwork.",
    "What do you call a shoe made out of bananas? A slipper",
    "I'm reading a horror book in Braille. Something bad is going to happen. I can feel it.",
    "Don't challenge Death to a pillow fight. Unless you're prepared for the reaper cushions",
    "What's the number one cause of divorce? Marriage",
    "I saw a rodent dancing to a Hall and Oates song, so I left. I can't gopher that.",
    "I saw someone stealing all my socks. I didn't go after them, because I got cold feet.",
    "Violence isn't the answer... It's the question and the answer is 'yes!'",
    "Where do you go if you're hurt while playing the game, 'Peek-A-Boo'? To the I. C. U.",
    "I accidently sprayed deodorant in my mouth  Now when I talk, I have weird axe scent.",
    "I dumped my last girlfriend because she was a communist. I should've known sooner. There were red flags everywhere",
    "My buddy called the Animal Welfare today and said, 'I have just found a suitcase in the woods containing four kittens.' 'That is terrible,' she replied, 'Are they moving?' 'I am not sure, to be honest' he said, 'But if they were that would explain the suitcase",
    "Rick Astley will let you borrow any of his disney movies, except one. He's never gonna give you UP",
    "What's the last thing to go through a bugs mind when it hits a windshield? It's butt",
    "If we are to be serious about saving the planet, we should stop printing calendars. They're the reason our days are numbered",
    "When I was at the airport and I witnessed a man collapse on the luggage carousel. I think he's ok: I saw him slowly coming round",
    "What happened when the oxymoron walked into the bar? There was a deafening silence",
    "Why did the shark blush? Because it saw the ocean's bottom",
    "Why can't you hear a pterodactyl using the bathroom? Because the pee is silent",
    "Did you hear about the guy who evaporated? He'll be mist!",
    "Writing crime novels is an okay job. It has its prose and cons",
    "Someone came into my house and stole all of my lightbulbs. I was delighted",
    "Getting hit in the funny bone may not actually be funny however, it is humerus",
    "In life, Bach was a composer. In death, he is a de-composer",
    "I lost my job at the sunscreen company. But I'm going to reapply",
    "My son has been eating electrical cords. So I grounded him until he conducts himself properly",
    "My friend gave up smoking cold turkey. He's doing better now but he's still coughing up feathers",
    "If athletes get athlete's foot. What do astronauts get? Missile toe",
    "What happened to the scientist that couldn't stop adding up the sides of precious gems? They became addicted to crystal math",
    "I was bullied into leveling my fishing. Yes, it's true, I caved to pier pressure",
    "Did you hear about the guy who invented the door knocker? He won the no-bell prize.",
    "Did you hear about the guys that tried to rob a Blood Bank? Yeah, they were caught red-handed.",
    "I knew a guy who was arrested for stealing hay. Unfortunately he couldn't make bale.",
    "There was a Roman emperor who never aged after he turned 19. His name was Constant Teen.",
    "9 out of 10 zoo dentists refuse to treat grizzly bears unless it's been given a STRONG anesthetic, proving true the old adage that... There's safety in numb-bears.",
    "Whoever invented the knock-knock joke should get a no bell prize.",
    "I decided to sell my Hoover… well it was just collecting dust.",
    "There once was a gnome king who was only 12 inches tall... He was a terrible king, but an amazing ruler.",
    "Nurse: Doctor, there's a patient that says he's invisible. Doctor: Well, tell him I can't see him right now!",
    "What is the hardest part about sky diving? The ground.",
    "Do you want a brief explanation of what an acorn is? In a nutshell, it's an oak tree.",
    "I made a pencil with two erasers. It was pointless.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "I ordered a chicken and an egg from Amazon. I'll let you know.",
    "Why do cows wear bells? Because their horns don't work.",
    "How do you make holy water? You boil the hell out of it.",
    "How do you get two whales in a car? Start in England and drive West.",
    "Did you hear about the guy who invented Lifesavers? They say he made a mint.",
    "Latest Mechagon news: After suffering weak gains at the poles, the National Transistor Party has been trying to energize its base",
    "I ordered a chicken and an egg online. I'll let you know.",
    "How come the stadium got hot after the game? Because all of the fans left.",
    "Sometimes I tuck my knees into my chest and lean forward.  That's just how I roll.",
    "I got a job at a Westfall farm but I resigned because they didn't have horses. I wanted something more stable",
    "Where do you learn to make banana splits? At sundae school.",
    "What was a more important invention than the first telephone? The second one.",
    "How many optometrists does it take to change a light bulb? 1 or 2? 1... or 2?",
    "My cat was just sick on the carpet, I don't think it's feline well.",
    "I have kleptomania, but when it gets bad, I take something for it.",
    "Why did Lord Chamberlain block the toilets in Darkhaven? The enema overflows.",
    "Whiteboards ... are remarkable.",
    "I've just written a song about a tortilla. Well, it is more of a rap really.",
    "Why did the Clydesdale give the pony a glass of water? Because he was a little horse!",
    "I just got fired from a florist, apparently I took too many leaves.",
    "One of my Alliance friend trolls so much he should have gone Horde",
    "How do you make a water bed more bouncy. You use Spring Water",
    "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
    "Mountains aren't just funny. They're hill areas.",
    "Why do bananas have to put on sunscreen before they go to the beach? Because they might peel!",
    "I knew a guy who collected candy canes, they were all in mint condition",
    "My dog used to chase people on a bike a lot. It got so bad I had to take his bike away.",
    "Leather is great for sneaking around because it's made of hide.",
    "What's red and bad for your teeth? A Brick.",
    "How do you fix a damaged jack-o-lantern? You use a pumpkin patch.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "Writing with a broken pencil is pointless.",
    "What do you do when your bunny gets wet? You get your hare dryer.",
    "Milk is also the fastest liquid on earth - its pasteurized before you even see it",
    "What is Alexstrasza's favorite instrument? The Wyrmrest accordion.",
    "How many dwarves does it take to screw in a lightbulb? Two. One to hold the light bulb in place and the other to drink until the room starts spinning",
    "What did one plate say to the other plate? Dinner is on me!",
    "What do you call a druid who melees in tree form? A combat log.",
    "How does Naxxramas fly? With its four wings.",
    "This morning I was wondering where the sun was, but then it dawned on me.",
    "I'm practicing for a bug-eating contest and I've got butterflies in my stomach.",
    "Did you hear about the bread factory burning down? They say the business is toast.",
    "Why did the belt go to prison? He held up a pair of pants!",
    "What do you call a pile of cats?  A Meowtain.",
    "Garrosh walks into a bar. The horde and the alliance form a line and punch him. Thats the punchline.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "So the Venthyr Covenant are getting a Voicechat of their own. It's called Venthyrlo",
    "The shovel was a ground-breaking invention.",
    "I have a joke about chemistry, but I don't think it will get a reaction.",
    "Why are fish easy to weigh? Because they have their own scales.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Where does Ragnaros go for his back treatments? The pyro-practor",
    "What do you call a bear with no teeth? A gummy bear!",
    "Two parrots are sitting on a perch. One turns to the other and asks, 'do you smell fish?'",
    "Velcro… What a rip-off.",
    "Two silk worms had a race. They ended up in a tie.",
    "Feral: Why do I always get drunk and fail my finals? Boomkin: You should stack int",
    "What do you call a beehive without the b's? An eehive.",
    "Did you know that ghosts call their true love their ghoul-friend?",
    "What do you call a gorilla wearing headphones? Anything you'd like, it can't hear you.",
    "Why did the kid throw the clock out the window? He wanted to see time fly!",
    "I just wrote a book on reverse psychology. Do not read it!",
    "What do you call a tauren rogue? Invisibull",
    "Why is the ocean always blue? Because the shore never waves back.",
    "'Hey, dad, did you get a haircut?' 'No, I got them all cut.'",
    "Why didn't the number 4 get into the nightclub? Because he is 2 square.",
    "As I suspected, someone has been adding soil to my garden. The plot thickens.",
    "A guy walks into a bar... and he was disqualified from the limbo contest.",
    "You will never guess what Elsa did to the balloon. She let it go.",
    "What did the vet say to the cat? How are you feline?",
    "What did one snowman say to the other snow man? Do you smell carrot?",
    "When Dad drops a pea off of his plate 'oh dear I've pee'd on the table!",
    "I hate perforated lines, they're tearable.",
    "Where does batman go to the bathroom? The batroom.",
    "What do you call a girl between two posts? Annette.",
    "This furniture store keeps emailing me, all I wanted was one night stand!",
    "I don't trust those trees. They seem kind of shady.",
    "What does garlic do when it gets hot? It takes its cloves off.",
    "'Put the cat out' … 'I didn't realize it was on fire",
    "What do you call a group of disorganized cats? A cat-tastrophe.",
    "What do you call a lazy baby kangaroo? A pouch potato!",
    "Shout out to my fingers. I can count on all of them.",
    "What do you call a belt made of watches? A waist of time.",
    "My son, a fire mage, asked me 'Mom, are we pyromaniacs?' I responded, 'Yes we arson'.",
    "My pet mouse 'Elvis' died last night. He was caught in a trap..",
    "I used to work for an origami company but they folded.",
    "They tried to make a diamond shaped like a duck. It quacked under the pressure.",
    "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
    "If the Queen Azshara accidentally farts during battle, pretend like nothing happens. Noble gasses should have no reaction",
    "Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base? Because there's a Shortstop in between!",
    "Why was the picture sent to prison? It was framed.",
    "Why do ducks make great detectives? They always quack the case.",
    "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
    "My dad told me a joke about boxing. I guess I missed the punch line.",
    "Did you hear about the runner who was criticized? He just took it in stride",
    "What did the zero say to the eight? That belt looks good on you.",
    "They laughed when I said I wanted to be a comedian - they're not laughing now.",
    "What does a clock do when it's hungry? It goes back four seconds!",
    "What do you call a crowd of chess players bragging about their wins in a hotel lobby? Chess nuts boasting in an open foyer.",
    "What does a bee use to brush its hair? A honeycomb!",
    "What did the beaver say to the tree? It's been nice gnawing you.",
    "How was the snow globe feeling after the storm? A little shaken.",
    "What did celery say when he broke up with his girlfriend? She wasn't right for me, so I really don't carrot all.",
    "I'm glad I know sign language, it's pretty handy.",
    "Sgt.: Commissar! Commissar! The troops are revolting! Commissar: Well, you're pretty repulsive yourself.",
    "What did the 0 say to the 8? Nice belt.",
    "What did the fish say when he hit the wall? Dam.",
    "What do I look like? A JOKE MACHINE!?",
    "Why do druids hate math? It gives them square roots.",
    "I got fired from the transmission factor, turns out I didn't put on enough shifts...",
    "What do prisoners use to call each other? Cell phones.",
    "How do you get a squirrel to like you? Act like a nut.",
    "What type of music do balloons hate? Pop music!",
    "Why do scuba divers fall backwards into the water? Because if they fell forwards they'd still be in the boat.",
    "Americans can't switch from pounds to kilograms overnight. That would cause mass confusion.",
    "What do you call a dictionary on drugs? High definition.",
    "Geology rocks, but Geography is where it's at!",
    "How do lawyers say goodbye? We'll be suing ya!",
    "Why did Bwonsamdi crossed the road? To get to de other side",
    "I got a reversible jacket for Christmas, I can't wait to see how it turns out.",
    "Every night at 11:11, I make a wish that someone will come fix my broken clock.",
    "Want to hear my pizza joke? Never mind, it's too cheesy.",
    "A butcher accidentally backed into his meat grinder and got a little behind in his work that day.",
    "Why is it so windy inside an arena? All those fans.",
    "Why do bees have sticky hair? Because they use honey combs!",
    "Did you hear about the kidnapping at school? It's ok, he woke up.",
    "How did the hipster burn the roof of his mouth? He ate the pizza before it was cool.",
    "Why does Monty, the gnomish flute player in Deeprun Tram, never miss a beat? He's a metro-gnome.",
    "There's not really any training for garbagemen. They just pick things up as they go.",
    "Why is there always a gate around cemeteries? Because people are always dying to get in.",
    "I had a dream that I was a muffler last night. I woke up exhausted!",
    "I am terrified of elevators. I'm going to start taking steps to avoid them.",
    "A man tried to sell me a coffin today. I told him that's the last thing I need.",
    "What did one hat say to the other? Stay here! I'm going on ahead.",
    "What do you call a death knight who doesn't wash? Sir Melly!",
    "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
    "My New Years resolution is to stop leaving things so late.",
    "How does a French skeleton say hello? Bone-jour.",
    "How many bones are in the human hand? A handful of them.",
    "What do you call 3 restro druids walking across private property? Trees passing",
    "I was going to tell a time-traveling joke, but you guys didn't like it.",
    "You know you have been playing WoW for too long when the microwave dings and you yell 'GRATS!'",
    "What do rogues and noobs have in common? They both pick locks.",
    "What is the leading cause of dry skin? Towels",
    "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
    "Did you hear the one about the guy with the broken hearing aid? Neither did he.",
    "Don't interrupt someone working intently on a puzzle. Chances are, you'll hear some crosswords.",
    "I had a neck brace fitted years ago and I've never looked back since.",
    "I asked Katy Stampwhistle for help with posting a pachyderm. I was having trouble addressing the elephant in the room",
    "What do you call a monkey in a mine field? A babooooom!",
    "Today, my son asked 'Can I have a book mark?' and I burst into tears. 11 years old and he still doesn't know my name is Brian.",
    "An apple a day keeps the bullies away. If you throw it hard enough.",
    "Mountains aren't just funny, they are hill areas",
    "I bought a dog from a blacksmith in town. As soon as I got him home he made a bolt for the door",
    "Did you hear about the cow who jumped over the barbed wire fence? It was udder destruction.",
    "How do robots eat guacamole? With computer chips.",
    "Wanna hear a joke about paper? Never mind—it's tearable.",
    "Why did the math book look so sad? Because of all of its problems!",
    "How can you tell a vampire has a cold? They start coffin.",
    "What did the mountain climber name his son? Cliff.",
    "What do you call two barracuda fish?  A Pairacuda!",
    "What's a robot's favorite snack? Computer chips.",
    "What concert costs just 45 cents? 50 Cent featuring Nickelback!",
    "Why don't seagulls fly over the bay? Because then they'd be bay-gulls!",
    "What do you get when you cross a rabbit with a water hose? Hare spray.",
    "What kind of pants do ghosts wear? Boo jeans.",
    "My wife said I should do lunges to stay in shape. That would be a big step forward.",
    "What did the left eye say to the right eye? Between us, something smells!",
    "It was raining cats and dogs the other day. I almost stepped in a poodle.",
    "Which is the fastest growing city in the world? 'Dublin'",
    "What did the judge say to the dentist? Do you swear to pull the tooth, the whole tooth and nothing but the tooth?",
    "What are the strongest days of the week? Saturday and Sunday...the rest are weekdays.",
    "Did you know crocodiles could grow up to 15 feet? But most just have 4.",
    "I am so good at sleeping I can do it with my eyes closed!",
    "Why did Billy get fired from the banana factory? He kept ng away the bent ones.",
    "Where does Napoleon keep his armies? In his sleevies.",
    "What do you call a group of killer whales playing instruments? An Orca-stra.",
    "Where do hamburgers go to dance? The meat-ball.",
    "What lies at the bottom of the ocean and twitches? A nervous wreck.",
    "Never take advice from electrons. They are always negative.",
    "How do you fix a broken pizza? With tomato paste.",
    "Why do mathematicians hate the U.S.? Because it's indivisible.",
    "How many Blizzard developers does it take to get an expansion right? Nobody knows yet",
    "How does the moon cut his hair? Eclipse it.",
    "What do you call a fake noodle? An impasta.",
    "What do you call a fibbing feral? A lion.",
    "I told my shadowlands gear that I loved it... It burst into tiers!",
    "Spring is here! I got so excited I wet my plants.",
    "It's hard to explain puns to kleptomaniacs, because they take everything literally.",
    "In the news a courtroom artist was arrested today, I'm not surprised, he always seemed sketchy.",
    "Just watched a documentary about beavers… It was the best damn program I've ever en.",
    "Why did the house go to the doctor? It was having window panes.",
    "Camping is intense.",
    "Remember, the best angle to approach a problem from is the 'try' angle.",
    "What do you call a pig with three eyes? Piiig",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "What did the ocean say to the shore? Nothing, it just waved.",
    "For Valentine's day, I decided to get my wife some beads for an abacus.  It's the little things that count.",
    "Why did the burglar hang his mugshot on the wall? To prove that he was framed!",
    "Egyptians claimed to invent the guitar, but they were such lyres.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "What do bees do after they are married? They go on a honeymoon.",
    "Plague, mana, and even Goblin-engineered.  When it comes to the Horde artillery, Theramore bombs",
    "Why did the miner get fired from his job? He took it for granite...",
    "Getting hit in the funny bone may not actually be funny however, it ihumerus",
    "What is a good Kul Tiran team building activity? The Drust fall",
    "How does a penguin build it's house? Igloos it together.",
    "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
    "How come a man driving a train got struck by lightning? He was a good conductor.",
    "You know, people say they pick their nose, but I feel like I was just born with mine.",
    "When my wife told me to stop impersonating a flamingo, I had to put my foot down.",
    "How does a druid cut their hair? 'Eclipse it.",
    "Some people say that comedians who tell one too many light bulb jokes soon burn out, but they don't know watt they are talking about. They're not that bright.",
    "Two peanuts were walking down the street. One was a salted.",
    "Why didn't the skeleton climb the mountain? It didn't have the guts.",
    "What do you get if you put a duck in a cement mixer? Quacks in the pavement.",
    "How does a taco say grace? Lettuce pray.",
    "What's the worst thing about ancient history class? The teachers tend to Babylon.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Our wedding was so beautiful, even the cake was in tiers.",
    "Why don't skeletons ride roller coasters? They don't have the stomach for it.",
    "Where does Fonzie like to go for lunch? Chick-Fil-Eyyyyyyyy.",
    "Why don't sharks eat clowns?  Because they taste funny.",
    "I made a belt out of watches once... It was a waist of time.",
    "What did the pirate say on his 80th birthday? Aye Matey!",
    "How do you stop a Warrior from charging? You take away his credit card",
    "Where do fruits go on vacation? Pear-is!",
    "The biggest knight at King Arthur's round table was Sir Cumference. He acquired his size from eating too much pi.",
    "Archaeology really is a career in ruins.",
    "How many tickles does it take to tickle an octopus? Ten-tickles!",
    "Why did the opera singer go sailing? They wanted to hit the high Cs.",
    "Why did the m&m go to school? Because it wanted to be a Smartie!",
    "I asked the surgeon if I could administer my own anesthetic, they said: go ahead, knock yourself out.",
    "I'll tell you what often gets over looked... garden fences.",
    "I used to play piano by ear. Now I use my hands.",
    "I gave my friend 10 puns hoping that one of them would make him laugh. Sadly, no pun in ten did.",
    "What has ears but cannot hear? A field of corn.",
    "Why can't a bicycle stand on its own? It's two-tired.",
    "What happens when you anger a brain surgeon? They will give you a piece of your mind.",
    "What's an astronaut's favorite part of a computer? The space bar.",
    "How does a scientist freshen their breath? With experi-mints!",
    "What did the big flower say to the littler flower? Hi, bud!",
    "At the boxing match, the dad got into the popcorn line and the line for hot dogs, but he wanted to stay out of the punchline.",
    "Did you hear the one about the giant pickle?  He was kind of a big dill.",
    "They say that you can safely fit 3 people on the expedition yak mount without a problem. I thought that sounded easy but finding 3 people without a problem is pretty hard.",
    "My friend told me that pepper is the best seasoning for a roast, but I took it with a grain of salt.",
    "A bartender broke up with her boyfriend, but he kept asking her for another shot.",
    "What has more letters than the alphabet? The post office!",
    "Did I tell you the time I fell in love during a backflip? I was heels over head!",
    "I invented a new word! Plagiarism!",
    "I broke my finger at work today, on the other hand I'm completely fine.",
    "What is a tornado's favorite game to play? Twister!",
    "Why is Peter Pan always flying? Because he Neverlands.",
    "I was thinking about moving to Moscow but there is no point Russian into things.",
    "Why did the kid cross the playground? To get to the other slide.",
    "What's the abbreviation for Death Knight? Decay",
    "What kind of tree fits in your hand? A palm tree!",
    "Why do trees seem suspicious on sunny days? Dunno, they're just a bit shady.",
    "Want to hear a chimney joke? Got stacks of em! First one's on the house",
    "How do locomotives know where they're going? Lots of training",
    "I got an A on my origami assignment when I turned my paper into my teacher",
    "I was going to get a brain transplant, but I changed my mind",
    "I used to be a banker, but I lost interest.",
    "Why did the coffee file a police report? It got mugged.",
    "Why do wizards clean their teeth three times a day? To prevent bat breath!",
    "The rotation of earth really makes my day.",
    "I applied to be a doorman but didn't get the job due to lack of experience. That surprised me, I thought it was an entry level position.",
    "Did you hear about the campsite that got visited by Bigfoot? It got in tents.",
    "How many kids with ADD does it take to change a lightbulb? Let's go ride bikes!",
    "Two peanuts were walking down the street. One was a salted",
    "Where do young cows eat lunch? In the calf-ateria.",
    "What do you call a dad that has fallen through the ice? A Popsicle.",
    "Today a girl said she recognized me from vegetarian club, but I'm sure I've never met herbivore.",
    "I just broke my guitar. It's okay, I won't fret",
    "Why are piggy banks so wise? They're filled with common cents.",
    "Where do young trees go to learn? Elementree school.",
    "Who is the coolest Doctor in the hospital? The hip Doctor!",
    "Bolvar had a full set of hair... He should be called Baldvar now.",
    "What do you call a cow with no legs? Ground beef.",
    "Why can't your nose be 12 inches long? Because then it'd be a foot!",
    "Why can shadow priests get away with not doing mechanics? Because they can just use a-vrm.",
    "What does an angry pepper do? It gets jalapeño face.",
    "You know that cemetery up the road? People are dying to get in there.",
    "What's the difference between an African elephant and an Indian elephant? About 5000 miles.",
    "What's the ifference between a guitar and a fishan tune a guitar but you can't 'tuna' fish!",
    "The invention of the wheel was what got things rolling",
    "When you have a bladder infection, urine trouble.",
    "What do clouds wear? Thunderwear.",
    "How do you know if there's an elephant under your bed? Your head hits the ceiling!",
    "'What time is it?' I don't know... it keeps changing.",
    "The Swiss must've been pretty confident in their chances of victory if they included a corkscrew in their army knife.",
    "I'm tired of following my dreams. I'm just going to ask them where they are going and meet up with them later.",
    "What kind of music do planets listen to? Nep-tunes.",
    "What do you call a fashionable lawn statue with an excellent sense of rhythmn? A metro-gnome",
    "Ben & Jerry's really need to improve their operation. The only way to get there is down a rocky road.",
    "Why couldn't the lifeguard save the hippie? He was too far out, man.",
    "They say vulpera are born wanderers and merchants. What's not known is their reverence for sliced meats and cheeses. There most popular business is also their spiritual leader and head caravaner. The Deli Llama.",
    "What did the dog say to the two trees? Bark bark.",
    "Dad I'm hungry' … 'Hi hungry I'm dad",
    "Why do choirs keep buckets handy? So they can carry their tune",
    "My boss told me to have a good day. So I went home...",
    "My sea sickness comes in wav.",
    "I cut my finger chopping cheese, but I think that I may haverater problems.",
    "Why was Pavlov's beard so soft?  Because he conditioned it.",
    "What do you call a guy lying on your doorstep? Matt.",
    "What do you call a sheep with no legs? A cloud.",
    "What country's capital is growing the fastest? Ireland. Every day it's Dublin.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Where do boats go when they're sick? To the boat doc.",
    "What time did the man go to the dentist? Tooth hurt-y.",
    "What do you give a sick lemon? Lemonaid.",
    "What do Alexander the Great and Winnie the Pooh have in common? Same middle name.",
    "I have the heart of a lion... and a lifetime ban from the San Diego Zoo.",
    "What kind of bagel can fly? A plain bagel.",
    "Why did Sweden start painting barcodes on the sides of their battleships? So they could Scandinavian.",
    "I'm only familiar with 25 letters in the English language. I don't know why.",
    "What do you call corn that joins the army? Kernel.",
    "Why was the robot angry? Because someone kept pressing his buttons!",
    "Is the pool safe for diving? It deep ends.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
    "It doesn't matter how much you push the envelope. It will still be stationary.",
    "What did the traffic light say to the car as it passed? 'Don't look I'm changing!'",
    "What do you call a cow on a trampoline? A milk shake!",
    "I knew I shouldn't steal a mixer from work, but it was a whisk I was willing to take.",
    "What concert costs only 45 cents? 50 cent featuring Nickelback.",
    "Two satellites decided to get married. The wedding wasn't much, but the reception was incredible.",
    "Why are ghosts bad liars? Because you can see right through them!",
    "Why did the cowboy have a weiner dog? Somebody told him to get a long little doggy.",
    "What did the grape do when he got stepped on? He let out a little wine.",
    "Coffee has a tough time at my house, every morning it gets mugged.",
    "I met this girl on a dating site and, I don't know, we just clicked.",
    "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
    "A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'",
    "Where do math teachers go on vacation? Times Square.",
    "Did you hear about the Mexican train killer? He had loco motives",
    "What do you call a droid that takes the long way around? R2 detour.",
    "What is a vampire's favorite fruit? A blood orange.",
    "What did the father tomato say to the baby tomato whilst on a family walk? Ketchup.",
    "Did you hear that David lost his ID in prague? Now we just have to call him Dav.",
    "Did you hear the news? FedEx and UPS are merging. They're going to go by the name Fed-Up from now on.",
    "What do you call an Argentinian with a rubber toe? Roberto",
    "Why aren't warriors using intellect enchants? Because they don't want their weapons to be smarter than themselves",
    "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
    "I couldn't figure out how the seat belt worked. Then it just clicked.",
    "What do you call a troublesome Canadian high schooler? A poutine.",
    "What is a witch's favorite subject in school? Spelling!",
    "What's the difference between a poorly dressed man on a tricycle and a well dressed man on a bicycle? Attire.",
    "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
    "A beekeeper was indicted after he confessed to years of stealing at work. They charged him with emBEEzlement",
    "I used to work in a shoe recycling shop. It was sole destroying.",
    "What's a rogue's favourite drink? Subtle tea.",
    "What did the coffee report to the police? A mugging.",
    "My boss told me to attach two pieces of wood together... I totally nailed it!",
    "What's a feral's favorite drink? Mice water",
    "I dreamed about drowning in an ocean made out of orange soda last night. It took me a while to work out it was just a Fanta sea.",
    "What kind of shoes do ninjas wear? Sneakers!",
    "How do you find Will Smith in the snow?  Look for fresh prints.",
    "I went to the store to pick up eight cans of sprite... when I got home I realized I'd only picked seven up",
    "What's Forest Gump's Facebook password? 1forest1",
    "I was going to learn how to juggle, but I didn't have the balls.",
    "Do I enjoy making courthouse puns? Guilty",
    "Why did the engineer create a robot fish battle pet? He wanted more e-fish in sea",
    "Have you ever tried to catch a fog? I tried yesterday but I mist.",
    "Why was it called the dark ages? Because of all the knights. ",
    "Did you hear about the new restaurant on the moon? The food is great, but there's just no atmosphere.",
    "Astronomers got tired watching the moon go around the earth for 24 hours. They decided to call it a day.",
    "Why do pirates not know the alphabet? They always get stuck at 'C'.",
    "How do you get an engineer to do something you want them to do? Tell them it's impossible",
    "You know you're addicted to WoW when the only reason you go to church is for the stam buff",
    "What did the ocean say to the beach? Thanks for all the sediment.",
    "What do you get from a pampered cow? Spoiled milk.",
    "I fear for the calendar, its days are numbered.",
    "Can February March? No, but April May!",
    "Have you heard about corduroy pillows?  They're making headlines!",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "How does dry skin affect you at work? You don't have any elbow grease to put into it.",
    "How do you make Lady Gaga cry? Poker face. ",
    "I saw a documentary on TV last night about how they put ships together.  It was rivetting.",
    "Did you know corduroy pillows are in style? They're making headlines.",
    "I couldn't get a reservation at the library. They were completely booked.",
    "What did the fish say when it swam into a wall? Damn!",
    "I gave all my dead batteries away today, free of charge.",
    "Why are Taurens so tired after giving birth? Because they have been de-calf-inated",
    "I was in an 80's band called the prevention. We were better than the cure.",
    "I wouldn't buy anything with velcro. It's a total rip-off.",
    "I once entered the rogues' world kleptomaniac championships. I took gold, silver, and bronze.",
    "What do you call two monkeys that share an Amazon account? Prime mates.",
    "I used to have a job at a calendar factory but I got the sack because I took a couple of days off.",
    "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
    "I went to the doctor today and he told me I had type A blood but it was a type O.",
    "What do you call it if a fire mage and paladin share a bath? A hot tub with bubbles",
    "What did the Dorito farmer say to the other Dorito farmer? Cool Ranch!",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "What happens when M&M's can't agree on anything? They reach an M-passe.",
    "Why does a Moon-rock taste better than an Earth-rock? Because it's a little meteor.",
    "Why is the new Kindle screen textured to look like paper? So you feel write at home.",
    "I been watching a channel on TV that is strictly just about origami — of course it is paper-view.",
    "I thought about going on an all-almond diet. But that's just nuts.",
    "Did you ar about the guy whose wle left side was cut off? He's all right now.",
    "Thanks for explaining the word 'many' to me. It means a lot.",
    "What's the best thing about elevator jokes? They work on so many levels.",
    "So one of my druid friends thought getting travel form would help him get girls... Sadly, he goes stag everywhere.",
    "My first time using an elevator was an uplifting experience. The second time let me down.",
    "What do you call a Tauren Demon Hunter? Illidairy",
    "How many apples grow on a tree? All of them!",
    "A horse walks into a bar. The bar tender says 'Hey.' The horse says 'Sure.'",
    "How does a penguin build its house? Igloos it together.",
    "I was at the library and asked if they have any books on 'paranoia', the librarian replied, 'yes, they are right behind you'",
    "Without geometry life is pointless.",
    "What did the Buffalo say to his little boy when he dropped him off at school? Bison.",
    "Feeling pretty proud of myself. The Sesame Street puzzle I bought said 3-5 years, but I finished it in 18 months.",
    "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
    "A paladin watered an avocado tree with holy water so they could make 'Holy Guacamole'",
    "What's E.T. short for? He's only got little legs.",
    "'Dad, I'm hungry.' Hello, Hungry. I'm Dad.",
    "Why are graveyards so noisy? Because of all the coffin.",
    "What did the calculator say to the student? You can count on me.",
    "Whenever the cashier at the grocery store asks my dad if he would like the milk in a bag he replies, 'No, just leave it in the carton!'",
    "Who did the wizard marry? His ghoul-friend",
    "Is this pool safe for diving? It deep ends.",
    "I went to a Foo Fighters Concert once... It was Everlong...",
    "A book just fell on my head. I only have my shelf to blame.",
    "What has three letters and starts with gas? A Car.",
    "What did one nut say as he chased another nut?  I'm a cashew!",
    "Last night me and my girlfriend watched three DVDs back to back. Luckily I was the one facing the TV.",
    "I wear a stethoscope so that in a medical emergency I can teach people a valuable lesson about assumptions.",
    "Bad at golf? Join the club.",
    "Want to hear a joke about construction? Nah, I'm still working on it.",
    "Why do bees hum? Because they don't know the words.",
    "If you walk into a forest and cut down a tree, but the tree doesn't understand why you cut it down, do you think it's stumped?",
    "I thought my wife was joking when she said she'd leave me if I didn't stop signing 'I'm A Believer'... Then I saw her face.",
    "What did the kul tiran crewmates find when they looked in the toilet? The captain's log",
    "I considered building the patio by myself. But I didn't have the stones.",
    "I was so proud when I finished the puzzle in six months, when on the side it said three to four years.",
    "Iron Man is technically a FEmale.",
    "What did Michael Jackson name his denim store? Billy Jeans!",
    "What do you call a careful wolf? Aware wolf.",
    "What happens to a frog's car when it breaks down? It gets toad.",
    "If you see a crime happen at the Apple store, what does it make you? An iWitness.",
    "I got fired from a florist, apparently I took too many leaves.",
    "Child: Dad, make me a sandwich. Dad: Poof! You're a sandwich.",
    "Chances are if you' ve seen one shopping center, you've seen a mall.",
    "I'd like to start a diet, but I've got too much on my plate right now.",
    "I like telling Dad jokes. Sometimes he laughs!",
    "Did you know you should always take an extra pair of pants golfing? Just in case you get a hole in one.",
    "Why do valley girls hang out in odd numbered groups? Because they can't even.",
    "I adopted my dog from a blacksmith. As soon as we got home he made a bolt for the door.",
    "Did you hear about the submarine industry? It really took a dive...",
    "Can I watch the TV? Dad: Yes, but don't turn it on.",
    "What do you call a poor Santa Claus? St. Nickel-less.",
    "It's only a murder of crows if there's probable caws.",
    "Yesterday a clown held a door open for me. I thought it was a nice jester.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
    "A man was caught stealing in a supermarket today while balanced on the shoulders of a couple of vampires. He was charged with shoplifting on two counts. ",
    "A doll was recently found dead in a rice paddy. It's the only known instance of a nick nack paddy wack.",
    "*Reversing the car* 'Ah, this takes me back'",
    "Why did the melons plan a big wedding? Because they cantaloupe!",
    "Why did the chicken get a penalty? For fowl play.",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why did the fireman wear red, white, and blue suspenders? To hold his pants up.",
    "Guy told me today he did not know what cloning is. I told him, 'that makes 2 of us.'",
    "What is this movie about? It is about 2 hours long.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "Did you hear about the two thieves who stole a calendar? They each got six months.",
    "Why should you never trust a pig with a secret? Because it's bound to squeal.",
    "I've just been reading a book about anti-gravity, it's impossible to put down!",
    "The first time I got a universal remote control I thought to myself, 'This changes everything'",
    "What is worse then finding a worm in your Apple? Finding half a worm in your Apple.",
    "Why did the A go to the bathroom and come out as an E? Because he had a vowel movement.",
    "There's a new type of broom out, it's sweeping the nation.",
    "When do doctors get angry? When they run out of patients.",
    "It takes guts to be an organ donor.",
    "I used to hate facial hair...but then it grew on me.",
    "Why did Dracula lie in the wrong coffin? He made a grave mistake.",
    "You know what they say about cliffhangers...",
    "A forsaken was searching for more help with his understaffed ship. All he had was a skeleton crew",
    "I just read a book about Stockholm syndrome. It was pretty bad at first, but by the end I liked it.",
    "I went to a book store and asked the saleswoman where the Self Help section was, she said if she told me it would defeat the purpose.",
    "Chromie was going to tell a time traveling joke... But you guys didn't like it.",
    "How do you tell the difference between a crocodile and an alligator? You will see one later and one in a while.",
    "What did the piece of bread say to the knife? Butter me up.",
    "I used to be a personal trainer. Then I gave my two week notice.",
    "How many South Americans does it take to change a lightbulb? A Brazilian",
    "How do you get a good price on a sled? You have toboggan.",
    "Past, present, and future walked into a bar.... It was tense.",
    "Who designs Kul Tiran pirate ships? ARGHHitects. Caaaarrrrrrrpenters build them and they have a large arrrrrrrrr&d department",
    "They're making a movie about clocks. It's about time",
    "How does Darth Vader like his toast? On the dark side.",
    "Why did the Kul'tirans settle in the southeastern area? Because they loved how Tiragarde Sounds",
    "What animal is always at a game of cricket? A bat.",
    "Why do worgan druids turn into cats? Because otherwise it would be ruff",
    "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
    "what do you call a dog that can do magic tricks? a labracadabrador",
    "What do you do on a remote island? Try and find the TV island it belongs to.",
    "Why can't you use 'Beef stew' as a password? Because it's not stroganoff.",
    "When is a door not a door? When it's ajar.",
    "The other day I was listening to a song about superglue, it's been stuck in my head ever since.",
    "What do you call a bee that lives in America? A USB.",
    "Why are guardian druids the best tanks for M+? They know all the best roots.",
    "I took the batteries out of the carbon monoxide alarm because the loud beeping was giving me a headache and making me feel sick and dizzy. - Ruthe Phoenix",
    "Which state has the most streets? Rhode Island.",
    "A steak pun is a rare medium well done.",
    "How do hens stay fit? They always egg-cercise!",
    "Why did the girl smear peanut butter on the road? To go with the traffic jam.",
    "Is there a hole in your shoe? No… Then how'd you get your foot in it?",
    "I'm on a whiskey diet. I've lost three days already.",
    "What do yocall your friend who stands in a hole? Phil.",
    "What do you get if you cross a gnome and a tauren? A mini-taur.",
    "Hear about the new restaurant called Karma? There's no menu: You get what you deserve.",
    "What do youall a nervous javelin thrower? Shakespeare.",
    "What do you call a sleepy balance druid? A napkin",
    "Every machine in the coin factory broke down all of a sudden without explanation. It just doesn't make any cents.",
    "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
    "Sore throats are a pain in the neck!",
    "Have you heard the rumor going around about butter? Never mind, I shouldn't spread it.",
    "If at first you don't succeed, sky diving is not for you!",
    "My friend said to me: 'What rhymes with orange' I said: 'no it doesn't'",
    "What kind of car does an egg drive? A yolkswagen.",
    "I am really disappointed that it is called The Dark Portal and not... Orc de Triomphe",
    "Did you hear about the guy who put a feral on a hot air balloon? It caused an uproar.",
    "Two fish are in a tank, one turns to the other and says, 'how do you drive this thing?'",
    "I used to be addicted to the hokey pokey, but I turned myself around.",
    "It's difficult to say what my wife does, she sells sea shells by the sea shore.",
    "What did the Red light say to the Green light? Don't look at me I'm changing!",
    "Atheism is a non-prophet organisation.",
    "Where did you learn to make ice cream? Sunday school.",
    "Shout out to my grandma, that's the only way she can hear.",
    "What do you call a speed contest where everyone is in denial? All lied races.",
    "Why does Norway have barcodes on their battleships? So when they get back to port, they can Scandinavian.",
    "That car looks nice but the muffler seems exhausted.",
    "Why didn't the skeleton cross the road? Because he had no guts.",
    "Why don't you startle Garrosh? Hellscream!",
    "Dad, did you get a haircut? No, I got them all cut!",
    "Dad, can you put my shoes on? I don't think they'll fit me.",
    "Did you hear about the cheese who saved the world? It was Legend-dairy!",
    "What is bread's favorite number?  Leaven.",
    "I've got a great joke about construction, but I'm still working on it.",
    "The best time on a clock is 6:30--hands down.",
    "What kind of dog lives in a particle accelerator? A Fermilabrador Retriever.",
    "R.I.P. boiled water. You will be mist.",
    "What do you call a dwarf signaling hello? A microwave",
    "Why couldn't the kid see the pirate movie? Because it was rated arrr!",
    "Why did the cookie cry? It was feeling crumby.",
    "What do you call a fat psychic? A four-chin teller.",
    "How come people get lost in Thunder Bluff? Because the layout makes a real mesa things",
    "To the person who stole my anti-depressant pills: I hope you're happy now.",
    "What did Romans use to cut pizza before the rolling cutter was invented? Lil Caesars",
    "Why do hunters get smashed in bars? Because they're always multi-shotting",
    "Do you know where you can get chicken broth in bulk? The stock market.",
    "How do you organize a space party? You planet.",
    "A young rogue robbed the Stormwind bank using a reflection prism but later turned himself in. Luckily, the judge was lenient as he saw a lot of himself noin the man.",
    "I decided to sell my vacuum cleaner—it was just gathering dust!",
    "We're renovating the house, and the first floor isoing great, but the second floor is another story.",
    "What kind of music do mummy's like? Rap",
    "What creature is smarter than a talking parrot? A spelling bee.",
    "Can a kangaroo jump higher than the Empire State Building? Of course. The Empire State Building can't jump.",
    "My boss told me to have a good day... so I went home.",
    "What musical instrument is found in the bathroom? A tuba toothpaste.",
    "Did you know that bells are one of the most requested items for Tauren player models? Mainly because their horns don't work.",
    "What's the longest word in the dictionary? Smiles. Because there's a mile between the two S's.",
    "I heard there was a new store called Moderation. They have everything there",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "What do you call a fish with no eyes? A fsh.",
    "Where do sheep go to get their hair cut? The baa-baa shop.",
    "I knew i shouldn't have ate that seafood. Because now i'm feeling a little… Eel",
    "I wish I could clean mirrors for a living. It's just something I can see myself doing.",
    "You c't trust atoms. They make up everything!",
    "This graveyard looks overcrowded. People must be dying to get in.",
    "Slept like a log last night … woke up in the fireplace.",
    "W are mummcared of vacation? They're afraid to unwind.",
    "Why are pirates called pirates? Because they arrr!",
    "So, I heard this pun about cows, but it's kinda offensive so I won't say it. I don't want there to be any beef between us. ",
    "A man is washing the car with his son. The son asks...... 'Dad, can't you just use a sponge?'",
    "If you thiwimming with dolphins is expensive, you should try swimming with sharks--it cost me an arm and a leg!",
    "When does a joke become a dad joke? When it becomes apparent.",
    "My wife is on a tropical fruit diet, the house is full of stuff. It is enough to make a mango crazy.",
    "I needed a password eight characters long so I picked Snow White and the Seven Dwarfs.",
    "I'm reading a book on the history of glue - can't put it down.",
    "Did you know that the Centaurs are generally considered attention seeking by the other races of Azeroth? Some say that they can't help but be the centaur of attention.",
    "My son is studying to be a surgeon, I just hope he makes the cut.",
    "Have you heard about the film 'Constipation', you probably haven't because it's not out yet.",
    "I asked a restro druid for help with my herb garden. They gave me some sage advice",
    "Doctor you've got to help me, I'm addicted to Twitter. Doctor: I don't follow you.",
    "'I'm sorry.' 'Hi sorry, I'm dad'",
    "How did Darth Vader know what Luke was getting for Christmas? He felt his presents.",
    "Why did the tree go to the dentist? It needed a root canal.",
    "Do you wanna box for your leftovers? No, but I'll wrestle you for them.",
    "How are false teeth like stars? They come out at night!",
    "What do you get hanging from Apple trees? Sore arms.",
    "Did you hear the rumor about butter? Well, I'm not going to spread it!",
    "What is the difference between a weasel and a stoat? One is weaselly identified. The other is stoatally different",
    "I used to think I was indecisive, but now I'm not sure.",
    "How do you get a baby alien to sleep?  You rocket.",
    "Why did the enchanter have to clean out his bank? Because it was full of dust",
    "What did the late tomato say to the early tomato? I'll ketch up",
    "Toasters were the first form of pop-up notifications.",
    "I ate a clock yesterday. It was so time consuming.",
    "Why are basketball players messy eaters? Because they are always dribbling.",
    "What do birds give out on Halloween? Tweets.",
    "I cut my finger cutting cheese. I know it may be a cheesy story but I feel grate now.",
    "I tried taking some high resolution photos of local farmland, but they all turned out a bit grainy.",
    "You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.",
    "I saw an ad in a shop window, 'Television for sale, $1, volume stuck on full', I thought, 'I can't turn that down'.",
    "Where do you take someone who has been injured in a Peek-a-boo accident? To the I.C.U.",
    "What did the orc yell to his companions after discovering the Un'goro Tar Pits? Look, tar!",
    "Why are fish so smart? Because they live in schools!",
    "What did the shy pebble wish for? That she was a little boulder.",
    "Why did the half blind man fall in the well? Because he couldn't see that well!",
    "Why do bees have sticky hair? Because they use a honeycomb.",
    "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
    "Somebody stole my Microsoft Office and they're going to pay - you have my Word.",
    "Why didn't the undead cross the road? He didn't have the guts",
    "What do you call a pony with a sore throat? A little hoarse.",
    "Some people eat light bulbs. They say it's a nice light snack.",
    "Why did the worker get fired from the orange juice factory? Lack of concentration.",
    "How did Harry Potter get down the hill? Walking. JK! Rowling.",
    "What do you call cheese by itself? Provolone.",
    "If Anduin is King in Elwynn Forest, what is he in Redridge Mountains? Hiking",
    "What's the sleepiest paper?apkin",
    "I'll tell you something about German sausages, they're the wurst",
    "How do the trees get on the internet? They log on.",
    "What's the best smelling insect? A deodor-ant.",
    "Man, I really love my furniture... me and my recliner go way back.",
    "Why do bears have hairy coats? Fur protection.",
    "Wife told me to take the spider out instead of killing it... We had some drinks, cool guy, wants to be a web developer.",
    "I really want to buy one of those supermarket checkout dividers, but the cashier keeps putting it back.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "I've been trying to come up with a dad joke about momentum . . . but I just can't seem to get it going.",
    "How do you follow Will Smith in the snow? You follow the fresh prints.",
    "Did you hear about the scientist who was lab partners with a pot of boiling water? He had a very esteemed colleague.",
    "What's a druid's favorite drink? Root beer",
    "What do you call 5 mogu rolling down the hill? The Rolling Stones",
    "Why was the broom late for the meeting? He overswept.",
    "Just read a few facts about frogs. They were ribbiting.",
    "Why are oranges the smartest fruit? Because they are made to concentrate. ",
    "What does a sprinter eat before a race? Nothing, they fast!",
    "A hunter missed their wedding because they disengaged",
    "What do you call a forsaken without a body and Nobody nose",
    "What does a lemon say when it answers the phone? Yellow!",
    "How do you make a tissue dance? You put a little boogie in it.",
    "My sister bet me $15 that I couldn't build a car out of spaghetti. You should have seen the look on her face as I drove pasta.",
    "What do you call someone with no nose? Nobody knows.",
    "What do computers and air conditioners have in common? They both become useless when you open windows.",
    "Why is no one friends with Dracula? Because he's a pain in the neck.",
    "If you're struggling to think of what to get someone for Christmas. Get them a fridge and watch their face light up when they open it.",
    "How do you email your guildmates in Bastion? You just click a-send",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks.",
    "A magician was driving down the street and then he turned into a driveway.",
    "What do you call a magician who has lost their magic? Ian.",
    "A man got hit in the head with a can of Coke, but he was alright because it was a soft drink.",
    "Why didn't the orange win the race? It ran out of juice.",
    "Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan.",
    "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
    "Ever wondered why bees hum? It's because they don't know the words.",
    "People who don't eat gluten are really going against the grain.",
    "Did you hear about the kidnapping at school? It's okay, he woke up.",
    "Why do chiccoops have two doors? Because if they had four they would be chicken sedans.",
    "Why did the naaru ask for a loan? It's because they were a bit light on money.",
    "If two vegans are having an argument, is it still considered beef?",
    "What kind of dinosaur loves to sleep? A stega-snore-us.",
    "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
    "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
    "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.",
    "I had a pair of racing snails. I removed their shells to make them more aerodynamic, but they became sluggish.",
    "Did you hear the joke about the wandering nun? She was a roman catholic.",
    "How do Forsaken without noses smell? Terrible!",
    "Why do you never see elephants hiding in trees? Because they're so good at it.",
    "Why is Peter Pan always flying? He neverlands.",
    "Where's the bin? Dad: I haven't been anywhere!",
    "How many hipsters does it take to change a lightbulb? Oh, it's a really obscure number. You've probably never heard of it.",
    "My dentist is the best, he even has a little plaque!",
    "How do you make 7 even? Take away the s.",
    "I tried to write a chemistry joke, but could never get a reaction.",
    "A woman is on trial for beating her husband to death with his guitar collection. Judge says, 'First offender?' She says, 'No, first a Gibson! Then a Fender!'",
    "Conjunctivitis.com - now that's a site for sore eyes.",
    "How can you tell if a tree is a dogwood tree? By its bark.",
    "I had a rough day, and then somebody went and ripped the front and back pages from my dictionary. It just goes from bad to worse.",
    "A cannibal is someone who is fed up with people.",
    "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.'",
    "What cheese can never be yours? Nacho cheese.",
    "Recent survey revealed 6 out of 7 dwarf's aren't happy.",
    "How much does a hipster weigh? An instagram.",
    "Breaking news! Energizer Bunny arrested - charged with battery.",
    "Why do crabs never give to charity? Because they're shellfish.",
    "I used to work for a soft drink can crusher. It was soda pressing.",
    "I think circles are pointless.",
    "How do you make a Kleenex dance? Put a little boogie in it!",
    "I started a new business making yachts in my attic this year...the sails are going through the roof",
    "What do you call an old snowman? Water.",
    "Did you hear about the chameleon who couldn't change color? They had a reptile dysfunction.",
    "What's black and white and read all over? The newspaper.",
    "If you see a crime at an Apple Store, does that make you an iWitness?",
    "I was fired from the keyboard factory yesterday.  I wasn't putting in enough shifts.",
    "What does a pirate pay for his corn? A buccaneer!",
    "Why does Superman get invited to dinners? Because he is a Supperhero.",
    "Why did the octopus beat the shark in a fight? Because it was well armed.",
    "The great thing about stationery shops is they're always in the same place...",
    "You have now! Did you hear Chromies time travel joke?",
    "Don't tell secrets in corn fields. Too many ears around.",
    "Have you heard of the band 1023MB? They haven't got a gig yet.",
    "I burned 2000 calories today, I left my food in the oven for too long.",
    "What did the digital clock say to the grandfather clock? Look, no hands!",
    "The treant Gnarlgar is an old, somewhat frail leader with a mysterious aura, but bad breath due to his diet and rough feet from walking everywhere... He is a super-calloused-fragile-mystic-hexed-by-halitosis.",
    "What's brown and sounds like a bell? Dung!",
    "Where do Kul Tiran pirates get their hooks? Second hand stores",
    "What did the Zen Buddist say to the hotdog vendor? Make me one with everything.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "What's blue and not very heavy?  Light blue.",
    "Can February march? No, but April may.",
    "Why did the barber win the race? He took a short cut.",
    "This is my step ladder. I never knew my real ladder.",
    "Which side of the chicken has more feathers? The outside.",
    "What did the scarf say to the hat? You go on ahead, I am going to hang around a bit longer.",
    "What do you call an eagle who can play the piano? Talonted!",
    "What do you call a cow with two legs? Lean beef.",
    "What did the restro druid say about the girl they didn't know? I've never met herbivore.",
    "When will the little snake arrive? I don't know but he won't be long...",
    "People saying 'boo! to their friends has risen by 85% in the last year.... That's a frightening statistic.",
    "My new thesaurus is terrible. In fact, it's so bad, I'd say it's terrible.",
    "When two vegans get in an argument, is it still called a beef?",
    "To the guy who invented zero... thanks for nothing.",
    "How much does it cost Santa to park his sleigh? Nothing, it's on the house.",
    "What do vegetarian zombies eat? Grrrrrainnnnnssss.",
    "I'm on a seafood diet. I see food and I eat it.",
    "A police officer caught two kids playing with a firework and a car battery. He charged one and let the other one off.",
    "I made a playlist for hiking. It has music from Peanuts, The Cranberries, and Eminem. I call it my Trail Mix.",
    "Did you know that protons have mass? I didn't even know they were catholic.",
    "What's a warlock's favorite drink? Shardonnay",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "Why are giraffes so slow to apologize? Because it takes them a long time to swallow their pride.",
    "Two dyslexics walk into a bra.",
    "My boss told me that he was going to fire the person with the worst posture. I have a hunch, it might be me.",
    "You can't trust a ladder. It will always let you down",
    "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
    "A quick shoutout to all of the sidewalks out there... Thanks for keeping me off the streets.",
    "What is a centipedes's favorite Beatle song?  I want to hold your hand, hand, hand, hand...",
    "To be Frank, I'd have to change my name.",
    "Don't trust atoms. They make up everything.",
    "You can't run through a camp site. You can only ran, because it's past tents.",
    "Why was Santa's little helper feeling depressed? Because he has low elf esteem.",
    "Dad, can you put the cat out? I didn't know it was on fire.",
    "Don't buy flowers at a monastery. Because only you can prevent florist friars.",
    "What happens when a strawberry gets run over crossing the street? Traffic jam.",
    "I went on a date last night with a girl from the zoo. It was great. She's a keeper.",
    "What do you call someone with no body and no nose? Nobody knows."
}

-- Register with Database Manager
Dadabase.DatabaseManager:RegisterModule("dadjokes", {
    name = "Dad Jokes",
    defaultContent = defaultJokes,
    dbVersion = 1,
    defaultSettings = {
        enabled = true,
        triggers = {
            wipe = true,
            death = false
        },
        groups = {
            raid = true,
            party = true
        }
    }
})

-- Register config tab
Dadabase.Config:RegisterModuleTab("dadjokes", {
    name = "Dad Jokes",
    buildContent = function(container, moduleId)
        Dadabase.Config:BuildModuleContent(container, moduleId)
    end
})
